# -*- coding: utf-8 -*-
"""05-embedding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KRl3_M5qxixK1jkLrqTGJaQ4w78E23kh
"""

!pip install langchain langchain-core langchain-community
!pip install openai
!pip install pypdf
!pip install tiktoken

import os
os.environ["OPENAI_API_KEY"] = "{YOUR_API_KEY}"
os.environ["AZURE_OPENAI_ENDPOINT"] = "YOUR_API_ENDPOINT"
os.environ["OPENAI_API_TYPE"] = "{YOUR_API_TYPE}"
os.environ["OPENAI_API_VERSION"] = "{YOUR_API_VERSION}"

from langchain.embeddings import AzureOpenAIEmbeddings

embeddings = AzureOpenAIEmbeddings(
                                    model="dev-text-embedding-3-small",
                                    chunk_size=500
                                  )

data = {
    "안녕하세요",
    "제 이름은 홍길동 입니다.",
    "이름이 무엇인가요?",
    "랭체인은 유용합니다",
    "Hello World"
}

embedded_data = embeddings.embed_documents(data)

len(embedded_data)

print(len(embedded_data[1]))

q = embeddings.embed_query("이 대화에서 언급된 인물은 무엇입니까?")
a = embeddings.embed_query("이 대화에서 언급된 인물은 홍길동 입니다. ")

from numpy import dot
from numpy.linalg import norm
import numpy as np

def cos_sim(A, B):
  return dot(A, B)/(norm(A)*norm(B))

print(cos_sim(q, a))
print(cos_sim(q, embedded_data[1]))
print(cos_sim(q, embedded_data[2]))
print(cos_sim(q, embedded_data[3]))
print(cos_sim(q, embedded_data[4]))

from langchain.embeddings import HuggingFaceBgeEmbeddings

model_name = "jhgan/ko-sbert-nli"
model_kwargs = {"device":"cpu"}
encode_kwargs = {"normalize_embeddings":True}
ko_embeddings = HuggingFaceBgeEmbeddings(
    model_name=model_name,
    model_kwargs=model_kwargs,
    encode_kwargs=encode_kwargs
)

embedded_data = ko_embeddings.embed_documents(data)
q = ko_embeddings.embed_query("이 대화에서 언급된 인물은 누구입니까?")
a = ko_embeddings.embed_query("이 대화에서 언급된 인물은 홍길동 입니다.")

print(len(embedded_data[0]))

print(cos_sim(q, a))
print(cos_sim(q, embedded_data[1]))
print(cos_sim(q, embedded_data[2]))
print(cos_sim(q, embedded_data[3]))
print(cos_sim(q, embedded_data[4]))

